// Generated by CoffeeScript 1.6.2
(function() {
  var asciiJSON, crypto, makeDummy,
    __hasProp = {}.hasOwnProperty;

  crypto = require('crypto');

  asciiJSON = exports;

  asciiJSON.isAscii = function(text) {
    return /^[\x00-\x7F]*$/.test(text);
  };

  asciiJSON.escapeNonAsciis = function(text) {
    var chars, code, i;

    chars = [];
    i = 0;
    while (i < text.length) {
      code = text.charCodeAt(i);
      if (code >= 128) {
        chars.push('\\u');
        chars.push(code.toString(16));
      } else {
        if (code < 32 || code === 34 || code === 92) {
          chars.push('\\');
        }
        chars.push(text[i]);
      }
      i++;
    }
    return chars.join('');
  };

  makeDummy = function() {
    return crypto.randomBytes(16).toString('hex');
  };

  asciiJSON.stringify = function(object) {
    var dummies, dummy, escaped, escapee, escapees, name, prison, value;

    escapees = 0;
    dummies = {};
    prison = {};
    for (name in object) {
      if (!__hasProp.call(object, name)) continue;
      value = object[name];
      if (typeof value !== 'string' || asciiJSON.isAscii(value)) {
        prison[name] = value;
      } else {
        escapees++;
        dummy = makeDummy();
        prison[name] = dummy;
        dummies[dummy] = asciiJSON.escapeNonAsciis(value);
      }
    }
    if (escapees === 0) {
      return JSON.stringify(object);
    } else {
      escaped = JSON.stringify(prison);
      for (dummy in dummies) {
        if (!__hasProp.call(dummies, dummy)) continue;
        escapee = dummies[dummy];
        escaped = escaped.replace(dummy, escapee);
      }
      return escaped;
    }
  };

  asciiJSON.parse = JSON.parse;

}).call(this);
